pivotal-cf/java-cfenv

README.adoc
Code sections were broken due to a little extra markup.
=> Removing extra markup

java-cfenv-boot/src/main/java/io/pivotal/cfenv/spring/boot/RedisCfEnvProcessor.java, java-cfenv-boot/src/test/java/io/pivotal/cfenv/spring/boot/RedisCfEnvProcessorTests.java, java-cfenv-boot/src/test/resources/io/pivotal/cfenv/spring/boot/test-redis-info-with-tls-port.json
Hi, 
We (the PCF Redis team) have exposed a tls_port in our CloudFoundry VCAP_SERVICES credentials. This PR allows Spring to automatically consume this tls_port and connect to Redis over SSL when possible. 
Best!
Mirah & @gregttn
=> Enable Redis SSL when Cloud Foundry credentials include tls_port.

README.adoc, java-cfenv-boot/src/main/java/io/pivotal/cfenv/spring/boot/CredHubCfEnvProcessor.java, java-cfenv-boot/src/main/resources/META-INF/spring.factories, java-cfenv-boot/src/test/java/io/pivotal/cfenv/spring/boot/CredHubCfEnvProcessorTests.java, java-cfenv-boot/src/test/resources/io/pivotal/cfenv/spring/boot/test-credhub-service.json
This adds support for binding credentials defined via the CredHub service broker.
=> Add support to pass credential defined in credhub to a bound application

java-cfenv-boot-pivotal-scs/pom.xml, java-cfenv-boot-pivotal-sso/pom.xml, java-cfenv-boot/pom.xml, java-cfenv-jdbc/pom.xml, java-cfenv-test-support/pom.xml, java-cfenv/pom.xml, pom.xml
This is how this library is consumed in a Java 11 project:
```
module foo {
requires java.cfenv;
requires java.cfenv.jdbc;
// And the rest of the modules...
}
```
Unfortunately, this produces the following warning:
>Name of automatic module 'java.cfenv' is unstable, it is derived from the module's file name.
That's because when a JAR does not contain a `module-info.class` Java assigns an automatic module name based on the JAR's name (`java-cfenv-2.2.2.RELEASE.jar` -> `java.cfenv`). The cheapest way to remove this warning is to define a custom automatic module name with the help of the `maven-jar-plugin`. That way, Java wouldn't have to infer the module's name from the name of the JAR.
See http://branchandbound.net/blog/java/2017/12/automatic-module-name/ for more info.
I've used the …
=> Add automatic module names for better consumption in Java 9 projects

ci/scripts/sync-to-maven-central.sh
Current quoting causes that '$BUILD_INFO artifactory-repo' is passed as 1 argument and so count validation in concourse-release-scripts fails.
=> Fix argument format in sync-to-maven-central.sh

java-cfenv-boot-pivotal-sso/src/main/java/io/pivotal/cfenv/boot/sso/CfSingleSignOnProcessor.java, java-cfenv-boot-pivotal-sso/src/main/java/io/pivotal/cfenv/boot/sso/SpringSecurityDetector.java
This allows oauth2 resource servers to be configured from SSO binding. Currently, it requires managing configuration manually.
=> Add support for bootstrapping oauth2 resource servers from SSO binding

java-cfenv/src/main/java/io/pivotal/cfenv/core/CfEnv.java, java-cfenv/src/test/java/io/pivotal/cfenv/core/CfEnvTests.java
This change makes it easier to test components using CfEnv to parse a given VCAP_SERVICES string.
As can be seen in CfEnv's tests, it is possible to mock `System.getenv` with JMockit, but patching globally scoped objects is quite invasive and also requires configuring a Java agent.
This change adds a second constructor to CfEnv, so that the VCAP_SERVICES value can simply be passed in.
A Spring Configuration class like the following...
```java
@Configuration
class FooConfiguration {
public FooConfiguration(Environment environment) {
this.environment = environment;
}
@Bean
public Foo foo() {
CfEnv cfEnv = new CfEnv(environment.get("VCAP_APPLICATION"), environment.get("VCAP_SERVICES"));
...
}
}
```
...can then be easily tested using `MockEnvironment`.
=> CfEnv: allow passing in values of VCAP_SERVICES & VCAP_APPLICATION

java-cfenv-jdbc/src/main/java/io/pivotal/cfenv/jdbc/SqlServerJdbcUrlCreator.java, java-cfenv-jdbc/src/test/java/io/pivotal/cfenv/jdbc/SqlServerJdbcTests.java, java-cfenv-jdbc/src/test/resources/io/pivotal/cfenv/jdbc/test-sqlserver-user-provided-info-with-props.json, java-cfenv-jdbc/src/test/resources/io/pivotal/cfenv/jdbc/test-sqlserver-user-provided-info.json
The SQLServer URI format of `sqlserver://username:passwordg@host:1433/database` was originally supported and then [removed](https://github.com/pivotal-cf/java-cfenv/commit/edd0068a988dda6795a68e0445ba08f23255cd8a). This change brought support for the format `sqlserver://host:1433;database=foo`.
This PR restores support for the original format which is a valid URL. It still supports the alternative format with semi-colons but because that is not a valid URL, we recommend using the original format when possible.
=> Restores support for user:pass@host/db style SQLServer URI

java-cfenv-jdbc/src/main/java/io/pivotal/cfenv/jdbc/DB2JdbcUrlCreator.java, java-cfenv-jdbc/src/test/java/io/pivotal/cfenv/jdbc/DB2JdbcTests.java
* so that username and password are properly transmitted to the drive
* provide same behavior as Spring SAR/ SCS connector: https://github.com/spring-cloud/spring-cloud-connectors/commit/a8eef2bdcbb5f177791d3843e2502db4c4dc32d8
=> Fix #231: remove url encoding for DB2

java-cfenv-boot/src/main/java/io/pivotal/cfenv/spring/boot/AmqpCfEnvProcessor.java, java-cfenv-boot/src/test/java/io/pivotal/cfenv/spring/boot/AmqpCfEnvProcessorTests.java, java-cfenv-boot/src/test/java/io/pivotal/cfenv/spring/boot/AmqpTestSupport.java, java-cfenv-boot/src/test/resources/io/pivotal/cfenv/spring/boot/test-rabbit-info-no-label-no-tags-secure-custom-port.json
In case it's not set (default) then replace it with 5671, to not break existing behaviour
=> Fix #220: Consider AMQPS port

gradle.properties, java-cfenv-jdbc/src/main/java/io/pivotal/cfenv/jdbc/DB2JdbcUrlCreator.java, java-cfenv-jdbc/src/test/java/io/pivotal/cfenv/jdbc/DB2JdbcTests.java, java-cfenv-jdbc/src/test/resources/io/pivotal/cfenv/jdbc/test-db2-realistic-payload-no-jdbc.json, java-cfenv-jdbc/src/test/resources/io/pivotal/cfenv/jdbc/test-db2-realistic-payload.json
* cfCredentials can have in its vcap service json payload other fields with the full jdbc url; this should be the priority to not loose any connection parameters
* DB2 driver does not support additional properties, it means username and password should not be provided additionally to the retrieved jdbcUrl
=> DB2 better url handling

buildSrc/src/main/groovy/io.pivotal.cfenv.java-conventions.gradle
* generated dependencies in pom have changed
With 
```
./gradlew clean :java-cfenv-test-support:generatePomFileForMavenJavaPublication
```
Before (assert 2):
```
<dependencies>
<dependency>
<groupId>io.pivotal.cfenv</groupId>
<artifactId>java-cfenv</artifactId>
<version>3.1.6-SNAPSHOT</version>
<scope>compile</scope>
</dependency>
<dependency>
<groupId>io.pivotal.cfenv</groupId>
<artifactId>java-cfenv</artifactId>
<version>3.1.6-SNAPSHOT</version>
<scope>compile</scope>
<type>test-jar</type>
</dependency>
[...]
</dependencies>
```
after (assert 1):
```
<dependencies>
<dependency>
<groupId>io.pivotal.cfenv</groupId>
<artifactId>java-cfenv</artifactId>
<version>3.1.6-SNAPSHOT</version>
<scope>compile</scope>
<type>test-jar</type>
</dependency>
</dependencies>
```
It's as if Gradle …
=> Arrange assertion

java-cfenv-jdbc/src/main/java/io/pivotal/cfenv/jdbc/MySqlJdbcUrlCreator.java, java-cfenv-jdbc/src/test/java/io/pivotal/cfenv/jdbc/MySqlJdbcTests.java, java-cfenv-jdbc/src/test/resources/io/pivotal/cfenv/jdbc/test-mariadb-info-jdbc-url-only.json, java-cfenv-jdbc/src/test/resources/io/pivotal/cfenv/jdbc/test-mariadb-info-jdbc-url.json, java-cfenv-jdbc/src/test/resources/io/pivotal/cfenv/jdbc/test-mariadb-info-uri.json, java-cfenv-jdbc/src/test/resources/io/pivotal/cfenv/jdbc/test-mariadb-info-with-label-no-tags.json, java-cfenv-jdbc/src/test/resources/io/pivotal/cfenv/jdbc/test-mariadb-info.json, java-cfenv/src/main/java/io/pivotal/cfenv/core/CfService.java
this is the followup to @daviddmd PR #224 - for some reason Github closed it when I tried and pushed the rebase and an additional commit 🤷‍♂️
=> Pr #224 - somehow I broke it

java-cfenv-boot/src/main/java/io/pivotal/cfenv/spring/boot/RedisCfEnvProcessor.java, java-cfenv-boot/src/test/java/io/pivotal/cfenv/spring/boot/RedisCfEnvProcessorTests.java
In Srping Boot 3.1, the flag is ssl.enbled not ssl, as in the java doc here: https://docs.spring.io/spring-boot/docs/3.1.8/api/org/springframework/boot/autoconfigure/data/redis/RedisProperties.Ssl.html#isEnabled()
=> Fix ssl enabled property in Redis config for Spring Boot 3.1

java-cfenv-docs/build.gradle, settings.gradle
The main goal is to avoid multiple Dependabot PRs when there's a new Asciidoctor Gradle release.
Additionally, fixes the docs project configuration, even though I see the module is not included and the docs are empty.
=> (main) Apply a resolutionStrategy to avoid Asciidoctor Gradle version multiple times

java-cfenv-boot-pivotal-scs/src/main/java/io/pivotal/cfenv/boot/scs/CfConfigClientProcessor.java, java-cfenv-boot-pivotal-scs/src/main/resources/META-INF/spring.factories, java-cfenv-boot-pivotal-scs/src/test/java/io/pivotal/cfenv/boot/scs/serviceregistry/CfConfigClientProcessorTest.java
Supports config-server OAuth2 properties in CF/TAS environment.  OAuth2 support is in place for service-registry but not for config-server.   
The primary consumer of these properties would be [spring-cloud-config-starters](https://github.com/pivotal-cf/spring-cloud-services-starters) which is currently unable to load configuration resource files due to missing oauth2 credentials.
=> Adds CfConfigClientProcessor to load config-server oauth properties

java-cfenv-boot/src/main/java/io/pivotal/cfenv/spring/boot/CfDataSourceEnvironmentPostProcessor.java, java-cfenv-boot/src/test/java/io/pivotal/cfenv/spring/boot/DataSourceTests.java, java-cfenv-boot/src/test/resources/vcap-services-tls.json
basically, I just rebased on main #262, and removed @gm2552 code for MariaDB since it was merged already (support for mariadb)
@pivotal-david-osullivan , I could push `spring-music` with this branch and still get, with a bound mariadb, those properties from the actuator
```
{
"name": "cfenvjdbc",
"properties": {
"spring.datasource.url": {
"value": "jdbc:mariadb://mad70744d.service.dc1.a9ssvc:3306/mad70744d?user=a9sa7fcc57a23fa9d05995dcd51c364&password=a9s6da4cc5f001593b8970eb5487f1fe148b281f476"
},
"spring.datasource.username": {
"value": "a9sa7fcc57a23fa9d05995dcd51c364"
},
"spring.datasource.password": {
"value": "a9s6da4cc5f001593b8970eb5487f1fe148b281f476"
},
"spring.datasource.driver-class-name": {
"value": "org.mariadb.jdbc.Driver"
},
"spring.r2dbc.url": {
"value": …
```
=> Greg main - replaces  Support for R2DBC connections in DataSource processor. #262 

gradle.properties, java-cfenv-all/build.gradle
* upgrade to latest Gradle Shadow plugin
* add new transformer that replaces the original package name in text files in the json-io config folder (aliases.txt, classFactory.txt, coercedTypes.txt, customWriters.txt) with the shaded one
=> Fix #275: Json-io shading needs additional transformer

java-cfenv-all/build.gradle
Reason: Task ':java-cfenv-all:generateMetadataFileForShadowPublication' uses this output of task ':java-cfenv-all:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
=> Fix ci: there was an issue during publishing

java-cfenv-boot-tanzu-genai/src/main/java/io/pivotal/cfenv/boot/genai/DefaultGenaiLocator.java
Making this more leinent against planned future versions of the tile where plans/endpoints may only contain MCP servers or Models.
=> chore: config endpoint may return null for models/mcp servers in the future
